### ISSUE TITLE
config problem for proteinprophet in linux

### ISSUE THREAD

**Issue by jd690764** [Nesvilab/philosopher#67] opened 2019-08-10 00:07 UTC
I am trying to use philosopher to process output from MSFragger on linux using the commandline script. ProteinProphet gives me this error:

philosopher proteinprophet --maxppmdiff 2000000 ./interact-Jurkat_WCL_100_Slot1-48_1_1013.pep.xml
INFO[17:00:02] Executing ProteinProphet v1.4.6
ProteinProphet (C++) by Insilicos LLC and LabKey Software, after the original Perl by A. Keller (TPP v5.2.1-dev Flammagenitus, Build 201906251008-exported (Linux-x86_64))
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
2019/08/09 17:00:03 open /tmp/6453c90b-61ee-4124-8b9f-e23767c3b50c/interact.prot.xml: no such file or directory

But, I can run ProteinProphet like this:

sudo /tmp/snap.philosopher/tmp/6453c90b-61ee-4124-8b9f-e23767c3b50c/ProteinProphet interact-Jurkat_WCL_100_Slot1-48_1_1013.pep.xml interact.prot.xml

This seems like a configuration issue for philosopher. Can you please help?

Thanks,
Janos

**Comment by prvst** [comment] 2019-08-12 19:02
Without looking at your system configuration and your script I would guess that something on the script might be set in a wrong way. Can you try running the different analysis steps manually through Philosopher ? Also check the output from PeptideProphet because if something went wrong in that step, Proteinprophet will not be able to run properly.

**Comment by jd690764** [comment] 2019-08-12 22:16
Hi Felipe,

Thank you for your reply. I attached a file with the commands and output
from the scripts. I appreciate your help.

Thanks,
Janos

**Comment by prvst** [comment] 2019-08-13 13:30
@jd690764, sorry I don't see your attachment

**Comment by jd690764** [comment] 2019-08-13 16:53
Hi Felipe,

Sorry about that - it should work now.

Janos

[log.txt](https://github.com/Nesvilab/philosopher/files/3498045/log.txt)

**Comment by jd690764** [comment] 2019-08-19 17:44
Hi Felipe,

did you have a chance to look at the output for the commands?

Thanks,
Janos

**Comment by prvst** [comment] 2019-08-19 18:24
Yes. Do you know why your ProteinProphet command is not showing in the log file ?

**Comment by jd690764** [comment] 2019-08-19 18:59
That is strange, I don't know. 

Here is the log again with the commands I ran manually just now. 

Thanks,
Janos
[log2.txt](https://github.com/Nesvilab/philosopher/files/3517266/log2.txt)

**Comment by prvst** [comment] 2019-08-19 19:21
@jd690764 This seems to be specific to your settings, I cannot reproduce this error here. I suggest that you try the pipeline command instead of using scripts because they might give you problems like that. Sorry for not being able to figure it out. I will close the issue, but please feel free to open it again if you find further problems.

**Closed by prvst** 2019-08-19 19:21 UTC
Labels: help wanted
